import * as core from '@actions/core';
import { VerificationResult } from '../types';
import { getGitHubCommentEngine, errorHandler, ErrorCategory, ErrorSeverity } from '../core';
import { GitHubServiceFactory } from '../core/github/GitHubServiceFactory';

/**
 * PR Reporter - Specialized reporter for visual regression testing results
 *
 * Uses centralized GitHubCommentEngine for comment posting, but provides
 * domain-specific formatting for verification results, screenshots, and
 * visual comparison data.
 *
 * Note: For generic PR comments, use GitHubCommentEngine directly.
 * This class is specifically for YoFix verification result formatting.
 */
export class PRReporter {
  private commentEngine = getGitHubCommentEngine();
  private prNumber: number;

  // Status emoji mappings
  private static readonly STATUS_EMOJIS = {
    success: '✅',
    partial: '⚠️',
    failure: '❌',
    running: '🔄',
    failed: '❌',
    skipped: '⏭️'
  } as const;

  private static readonly SEVERITY_ICONS = {
    critical: '🚨',
    warning: '⚠️',
    info: 'ℹ️'
  } as const;

  constructor() {
    // Comment engine is already initialized globally
    // Use GitHubServiceFactory to get context
    const githubService = GitHubServiceFactory.getService();
    const context = githubService.getContext();
    this.prNumber = context.prNumber;

    if (!this.prNumber) {
      core.warning('No PR number found, cannot post comment');
    }
  }

  /**
   * Post comprehensive verification results to PR
   */
  async postResults(result: VerificationResult, storageConsoleUrl?: string): Promise<void> {
    if (!this.prNumber) {
      core.warning('No PR number found, cannot post comment');
      return;
    }
    
    try {
      core.info(`Posting verification results to PR #${this.prNumber}...`);
      
      const comment = this.generateCommentBody(result, storageConsoleUrl);
      
      await this.commentEngine.postComment(comment, {
        updateExisting: true,
        signature: 'yofix-verification-results'
      });
      
      core.info('Posted verification results to PR');
    } catch (error) {
      await errorHandler.handleError(error as Error, {
        severity: ErrorSeverity.HIGH,
        category: ErrorCategory.GITHUB,
        location: 'pr-reporter'
      });
      throw error;
    }
  }

  /**
   * Post a simple status update (for early failures)
   */
  async postStatusUpdate(status: 'running' | 'failed' | 'skipped', message: string): Promise<void> {
    if (!this.prNumber) {
      core.warning('No PR number found, cannot post status update');
      return;
    }
    
    try {
      const statusEmoji = PRReporter.STATUS_EMOJIS[status];

      const comment = `## ${statusEmoji} Runtime PR Verification

**Status**: ${status.charAt(0).toUpperCase() + status.slice(1)}

${message}

---
*Generated by [YoFix](https://github.com/yofix/yofix) • ${new Date().toLocaleString()}*`;

      await this.commentEngine.postComment(comment, {
        updateExisting: true,
        signature: 'yofix-status-update'
      });
    } catch (error) {
      await errorHandler.handleError(error as Error, {
        severity: ErrorSeverity.MEDIUM,
        category: ErrorCategory.GITHUB,
        location: 'pr-reporter',
        recoverable: true
      });
    }
  }

  /**
   * Generate comprehensive comment body with React-specific results
   */
  private generateCommentBody(result: VerificationResult, storageConsoleUrl?: string): string {
    const statusEmoji = PRReporter.STATUS_EMOJIS[result.status] || PRReporter.STATUS_EMOJIS.failure;

    // Get framework name from route-impact-analyzer or fallback to generic
    const frameworkName = result.framework || 'Web App';

    // Header with overall status
    let comment = `## ${statusEmoji} Runtime PR Verification - ${frameworkName}\n\n`;

    // Test summary
    comment += `**Test Results**: ${result.passedTests}/${result.totalTests} passed`;
    if (result.failedTests > 0) {
      comment += ` • ${result.failedTests} failed`;
    }
    if (result.skippedTests > 0) {
      comment += ` • ${result.skippedTests} skipped`;
    }
    comment += ` • ${this.formatDuration(result.duration)}\n\n`;

    // Quick access links
    const screenshots = result.testResults.flatMap(t => t.screenshots);
    const videos = result.testResults.flatMap(t => t.videos);
    
    if (screenshots.length > 0 || videos.length > 0) {
      comment += `**Visual Evidence**: `;
      comment += `📸 ${screenshots.length} screenshot${screenshots.length !== 1 ? 's' : ''}`;
      if (videos.length > 0) {
        comment += ` • 🎥 ${videos.length} video${videos.length !== 1 ? 's' : ''}`;
      }
      if (storageConsoleUrl) {
        comment += ` • [Firebase Console](${storageConsoleUrl})`;
      }
      comment += '\n\n';
    }

    // Embed screenshots directly
    if (screenshots.length > 0) {
      core.info(`Embedding ${screenshots.length} screenshots in PR comment`);
      const screenshotsWithUrls = this.filterWithUrls(screenshots);
      core.info(`Screenshots with Firebase URLs: ${screenshotsWithUrls.length}`);

      // Always use unified comparison table structure (handles missing baselines gracefully)
      comment += this.generateVisualComparisonTable(screenshots, result);
    }
    
    // Embed videos directly
    if (videos.length > 0) {
      core.info(`Embedding ${videos.length} videos in PR comment`);
      const videosWithUrls = this.filterWithUrls(videos);
      core.info(`Videos with Firebase URLs: ${videosWithUrls.length}`);
      
      comment += this.generateEmbeddedVideos(videos);
    }


    // Expandable details section
    comment += '<details>\n<summary><strong>View Detailed Results</strong></summary>\n\n';

    // Issues found section
    if (result.summary.issuesFound.length > 0) {
      comment += '### ⚠️ Issues Detected\n\n';
      for (const issue of result.summary.issuesFound.slice(0, 5)) {
        comment += `- ${issue}\n`;
      }
      if (result.summary.issuesFound.length > 5) {
        comment += `- ...and ${result.summary.issuesFound.length - 5} more issues\n`;
      }
      comment += '\n';
    }

    // Firebase configuration details
    comment += '### 🔥 Firebase Configuration\n\n';
    comment += `- **Project**: \`${result.firebaseConfig.projectId}\`\n`;
    comment += `- **Target**: \`${result.firebaseConfig.target}\`\n`;
    comment += `- **Build System**: ${result.firebaseConfig.buildSystem === 'vite' ? 'Vite' : 'Create React App'}\n`;
    comment += `- **Preview URL**: [${result.firebaseConfig.previewUrl}](${result.firebaseConfig.previewUrl})\n\n`;

    // Performance metrics
    const consoleErrors = result.testResults.flatMap(t => 
      t.consoleMessages.filter(m => m.type === 'error')
    );
    
    if (consoleErrors.length > 0) {
      comment += '### 🐛 Console Errors\n\n';
      comment += `Found ${consoleErrors.length} console error${consoleErrors.length !== 1 ? 's' : ''} during testing:\n\n`;
      for (const error of consoleErrors.slice(0, 3)) {
        comment += `- \`${error.text.substring(0, 100)}${error.text.length > 100 ? '...' : ''}\`\n`;
      }
      if (consoleErrors.length > 3) {
        comment += `- ...and ${consoleErrors.length - 3} more errors\n`;
      }
      comment += '\n';
    }

    comment += '</details>\n\n';

    // Footer
    const timestamp = new Date().toLocaleString();
    comment += `---\n*Generated by [YoFix](https://github.com/yofix/yofix) • ${timestamp}*`;

    return comment;
  }

  /**
   * Helper: Format viewport dimensions
   */
  private formatViewport(viewport: { width: number; height: number }): string {
    return `${viewport.width}×${viewport.height}`;
  }

  /**
   * Helper: Filter items that have Firebase URLs
   */
  private filterWithUrls<T extends { firebaseUrl?: string }>(items: T[]): T[] {
    return items.filter(item => item.firebaseUrl);
  }

  /**
   * Helper: Get route from screenshot object
   */
  private getRouteFromScreenshot(screenshot: any): string {
    return screenshot.route || this.extractRouteFromScreenshotName(screenshot.name) || '/';
  }

  /**
   * Helper: Group screenshots by route
   */
  private groupScreenshotsByRoute(screenshots: any[]): Record<string, any[]> {
    return screenshots.reduce((acc, screenshot) => {
      const route = this.getRouteFromScreenshot(screenshot);
      if (!acc[route]) {
        acc[route] = [];
      }
      acc[route].push(screenshot);
      return acc;
    }, {} as Record<string, any[]>);
  }

  /**
   * Helper: Get severity icon based on severity level
   */
  private getSeverityIcon(severity: 'critical' | 'warning' | 'info'): string {
    return PRReporter.SEVERITY_ICONS[severity];
  }

  /**
   * Helper: Get diff severity icon based on percentage
   */
  private getDiffSeverityIcon(diffPercentage: number): string {
    if (diffPercentage > 5) return PRReporter.SEVERITY_ICONS.critical;
    if (diffPercentage > 1) return PRReporter.SEVERITY_ICONS.warning;
    return PRReporter.SEVERITY_ICONS.info;
  }

  /**
   * Format duration in human-readable format
   */
  private formatDuration(durationMs: number): string {
    if (durationMs < 1000) {
      return `${durationMs}ms`;
    } else if (durationMs < 60000) {
      return `${(durationMs / 1000).toFixed(1)}s`;
    } else {
      const minutes = Math.floor(durationMs / 60000);
      const seconds = ((durationMs % 60000) / 1000).toFixed(0);
      return `${minutes}m ${seconds}s`;
    }
  }

  /**
   * Generate visual comparison table with baseline vs current screenshots
   */
  private generateVisualComparisonTable(screenshots: any[], result: VerificationResult): string {
    if (screenshots.length === 0) {
      return '';
    }

    // Group screenshots by route
    const groupedByRoute = this.groupScreenshotsByRoute(screenshots);

    // Generate summary statistics
    const totalRoutes = Object.keys(groupedByRoute).length;
    const routesWithIssues = Object.values(groupedByRoute).filter((screenshots: any[]) => 
      screenshots.some(s => s.comparison?.hasDifference || s.comparison?.issues?.length > 0)
    ).length;
    const newRoutes = Object.values(groupedByRoute).filter((screenshots: any[]) =>
      screenshots.some(s => s.comparison?.status === 'new')
    ).length;

    let content = `## 📸 Visual Testing Results\n\n`;
    content += `### 🎯 Summary: ${totalRoutes} route${totalRoutes !== 1 ? 's' : ''} tested`;
    if (routesWithIssues > 0) {
      content += ` • ⚠️ ${routesWithIssues} with issues`;
    }
    if (newRoutes > 0) {
      content += ` • 🆕 ${newRoutes} new`;
    }
    content += `\n\n`;

    // Generate collapsible sections for each route
    for (const [route, routeScreenshots] of Object.entries(groupedByRoute)) {
      const routeHasIssues = (routeScreenshots as any[]).some(s => 
        s.comparison?.hasDifference || s.comparison?.issues?.length > 0
      );
      const isNewRoute = (routeScreenshots as any[]).some(s => s.comparison?.status === 'new');
      
      const statusIcon = isNewRoute ? '🆕' : routeHasIssues ? '⚠️' : '✅';
      const statusText = isNewRoute ? 'New Route' : routeHasIssues ? 'Issues Detected' : 'No Issues';

      content += `<details>\n`;
      content += `<summary><strong>📍 ${route}</strong> - ${statusIcon} ${statusText}</summary>\n\n`;

      // Get production URL (if available from configuration) and preview URL
      const productionUrl = this.getProductionUrl();
      const previewUrl = this.getBasePreviewUrl(result);

      // Create comparison table headers with links
      const baselineHeader = productionUrl
        ? `Baseline ([Production ↗](${productionUrl}${route}))`
        : `Baseline (Production)`;
      const currentHeader = `Current ([Preview ↗](${previewUrl}${route}))`;

      content += `| ${baselineHeader} | ${currentHeader} | Comparison |\n`;
      content += `|${'-'.repeat(baselineHeader.length + 2)}|${'-'.repeat(currentHeader.length + 2)}|------------|\n`;

      // Sort by viewport size (desktop first)
      const sortedScreenshots = (routeScreenshots as any[]).sort((a, b) => b.viewport.width - a.viewport.width);

      for (const screenshot of sortedScreenshots) {
        content += this.generateComparisonTableRow(screenshot);
      }
      
      // Add issues section if any
      const allIssues = (routeScreenshots as any[]).flatMap(s => s.comparison?.issues || []);
      if (allIssues.length > 0) {
        content += `\n**Issues Found:**\n`;
        for (const issue of allIssues) {
          const severityIcon = this.getSeverityIcon(issue.severity || 'info');
          content += `- ${severityIcon} **${issue.type}**: ${issue.description}\n`;
          if (issue.fix) {
            content += `  - 🔧 **Fix**: ${issue.fix}\n`;
          }
        }
      }
      
      content += `\n</details>\n\n`;
    }

    return content;
  }

  /**
   * Generate a single row for the comparison table
   */
  private generateComparisonTableRow(screenshot: any): string {
    // Viewport with optional duration
    const durationText = screenshot.duration ? ` • ${this.formatDuration(screenshot.duration)}` : '';
    const viewport = `**${this.formatViewport(screenshot.viewport)}**${durationText}`;

    // Baseline column - only show viewport/duration if baseline exists
    let baselineCell = '';
    if (screenshot.baseline?.url) {
      const updatedDate = screenshot.baseline.updatedDate || 'Unknown';
      baselineCell = `${viewport}<br/>![Baseline](${screenshot.baseline.url})<br/>*Updated: ${updatedDate}*`;
    } else if (screenshot.comparison?.status === 'new') {
      baselineCell = '🆕 *New baseline created*';
    } else {
      baselineCell = '🆕 *No baseline available*';
    }

    // Current screenshot column (includes viewport info and consistent date format)
    let currentCell = `${viewport}<br/>`;
    if (screenshot.firebaseUrl) {
      const captureDate = new Date(screenshot.timestamp).toLocaleDateString('en-US', {
        month: 'short',
        day: 'numeric',
        year: 'numeric'
      });
      currentCell += `![Current](${screenshot.firebaseUrl})<br/>*Captured: ${captureDate}*`;
    } else {
      currentCell += '❌ *Screenshot not available*';
    }
    
    // Comparison column
    let comparisonCell = '';
    if (screenshot.comparison) {
      const comp = screenshot.comparison;
      switch (comp.status) {
        case 'new':
          comparisonCell = `🆕 **New Route**<br/>Baseline created from current`;
          break;
        case 'unchanged':
          comparisonCell = `✅ **${comp.diffPercentage.toFixed(2)}% diff**<br/>No issues detected`;
          break;
        case 'changed':
          // Use more precision for very small differences
          const displayPercentage = comp.diffPercentage < 0.01
            ? comp.diffPercentage.toFixed(4)
            : comp.diffPercentage.toFixed(2);
          const diffIcon = this.getDiffSeverityIcon(comp.diffPercentage);
          comparisonCell = `${diffIcon} **${displayPercentage}% diff**<br/>`;
          if (comp.diffImageUrl) {
            comparisonCell += `[View Diff](${comp.diffImageUrl})`;
          } else {
            comparisonCell += 'Visual changes detected';
          }
          break;
        case 'error':
          // Extract error details if available
          let errorMsg = comp.metrics?.error || 'Unable to compare images';

          // Provide helpful context for dimension mismatches
          if (errorMsg.includes('dimensions do not match')) {
            errorMsg = errorMsg.replace(
              'Image dimensions do not match:',
              '📏 **Dimension Mismatch**<br/>Images have different sizes:'
            );
            errorMsg += '<br/><br/>ℹ️ **Why?** Baseline was captured at different settings (likely viewport-only vs full-page)';
            errorMsg += '<br/>🔧 **Fix:** Delete old baselines from storage and re-run to create new full-page baselines';
          }

          comparisonCell = `❌ **Cannot Compare**<br/>${errorMsg}`;
          break;
        default:
          comparisonCell = `❓ **Unknown Status**`;
      }
      
      // Add issue summary if any
      if (comp.issues && comp.issues.length > 0) {
        const criticalIssues = comp.issues.filter(i => i.severity === 'critical').length;
        const warningIssues = comp.issues.filter(i => i.severity === 'warning').length;
        if (criticalIssues > 0) {
          comparisonCell += `<br/>🚨 ${criticalIssues} critical issue${criticalIssues !== 1 ? 's' : ''}`;
        }
        if (warningIssues > 0) {
          comparisonCell += `<br/>⚠️ ${warningIssues} warning${warningIssues !== 1 ? 's' : ''}`;
        }
      }
    } else {
      // No comparison data available (first run without baseline comparison step)
      comparisonCell = '🆕 **First Run**<br/>Establishing baseline';
    }

    return `| ${baselineCell} | ${currentCell} | ${comparisonCell} |\n`;
  }

  /**
   * Extract route name from screenshot filename
   */
  private extractRouteFromScreenshotName(screenshotName: string): string {
    // Remove viewport size pattern and file extension
    let route = screenshotName.replace(/-\d+x\d+.*$/, '').replace(/\.(png|jpg|jpeg)$/, '');
    // Convert back to route format
    route = route.replace(/_/g, '/');
    if (!route.startsWith('/')) {
      route = '/' + route;
    }
    if (route === '/root' || route === '/') {
      return '/';
    }
    return route;
  }

  /**
   * Get base preview URL without trailing slash
   */
  private getBasePreviewUrl(result: VerificationResult): string {
    return result.firebaseConfig.previewUrl.replace(/\/$/, '');
  }

  /**
   * Get production URL from configuration (if available)
   */
  private getProductionUrl(): string | null {
    // Try to get from environment variable (GitHub Actions input)
    const productionUrl = process.env.INPUT_PRODUCTION_URL || process.env.PRODUCTION_URL;
    if (productionUrl) {
      return productionUrl.replace(/\/$/, ''); // Remove trailing slash
    }
    return null;
  }


  /**
   * Generate embedded videos for PR comment
   */
  private generateEmbeddedVideos(videos: any[]): string {
    if (videos.length === 0) {
      return '';
    }

    let gallery = '### 🎥 Test Videos\n\n';

    // Only show videos that have Firebase URLs
    const videosWithUrls = this.filterWithUrls(videos);
    
    if (videosWithUrls.length === 0) {
      gallery += '_Videos captured but URLs not available_\n\n';
      return gallery;
    }
    
    // GitHub doesn't support video embedding, so we'll create nice preview links
    // with video thumbnails if possible
    gallery += '<table>\n';
    
    // Create rows of 3 videos each
    for (let i = 0; i < videosWithUrls.length; i += 3) {
      gallery += '<tr>\n';
      
      for (let j = i; j < Math.min(i + 3, videosWithUrls.length); j++) {
        const video = videosWithUrls[j];
        gallery += `<td align="center" width="33%">\n`;
        gallery += `<a href="${video.firebaseUrl}">\n`;
        // Use a play button emoji as a visual indicator
        gallery += `<div>🎬</div>\n`;
        gallery += `<strong>${video.name.replace(/\.(webm|mp4)$/, '')}</strong><br>\n`;
        gallery += `<em>${this.formatDuration(video.duration)}</em><br>\n`;
        gallery += `<kbd>▶️ Click to Play</kbd>\n`;
        gallery += `</a>\n`;
        gallery += `</td>\n`;
      }
      
      // Fill empty cells if needed
      for (let k = videosWithUrls.length % 3; k < 3 && k > 0 && i + 3 > videosWithUrls.length; k++) {
        gallery += `<td></td>\n`;
      }
      
      gallery += '</tr>\n';
    }
    
    gallery += '</table>\n\n';
    
    // Add direct links as well
    gallery += '<details>\n<summary>Direct video links</summary>\n\n';
    for (const video of videosWithUrls) {
      gallery += `- [${video.name}](${video.firebaseUrl}) - ${this.formatDuration(video.duration)}\n`;
    }
    gallery += '\n</details>\n\n';

    return gallery;
  }

  /**
   * Generate compact status badge for quick overview
   */
  generateStatusBadge(result: VerificationResult): string {
    const status = result.status;
    const color = status === 'success' ? 'brightgreen' : status === 'partial' ? 'yellow' : 'red';
    const tests = `${result.passedTests}/${result.totalTests}`;
    
    return `![Tests](https://img.shields.io/badge/tests-${tests}-${color}) ![Status](https://img.shields.io/badge/status-${status}-${color})`;
  }
}