name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Lint
        run: npm run lint || true  # Skip lint errors temporarily
        
      - name: Type check
        run: npm run typecheck
        
      - name: Test
        run: npm test
        env:
          CI: true
          
      - name: Build
        run: npm run build
        
      - name: Verify dist
        run: |
          if [ -n "$(git status --porcelain dist/)" ]; then
            echo "::error::dist/ folder has uncommitted changes"
            echo "Please run 'npm run build' locally and commit the changes"
            git status --porcelain dist/
            exit 1
          fi
          
      - name: Test Action
        uses: ./
        with:
          preview-url: 'https://example.com'
          github-token: ${{ secrets.YOFIX_GITHUB_TOKEN }}
          claude-api-key: 'test-key'
          storage-provider: 'firebase'
          firebase-credentials: ${{ secrets.TEST_FIREBASE_CREDS || 'eyJ0ZXN0IjoidGVzdCJ9' }}
          storage-bucket: 'test-bucket'
        continue-on-error: true  # Don't fail on test run

  security:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Run security audit
        run: yarn audit --production || true  # Don't fail on audit issues for now
        
      - name: Check for secrets
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.pull_request.base.sha || github.event.before || github.event.repository.default_branch }}
          head: ${{ github.event.pull_request.head.sha || github.sha || 'HEAD' }}
          extra_args: --debug --only-verified

  compatibility:
    strategy:
      matrix:
        node: ['18', '20']
        os: [ubuntu-latest, macos-latest]
        
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Build
        run: npm run build
        
      - name: Test
        run: npm test