name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3
          
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          # Rebuild native modules with verbose output for debugging
          npm rebuild --verbose || echo "Native rebuild failed, continuing..."
        
      - name: Build
        run: yarn build
        
      - name: Test
        run: yarn test
        env:
          CI: true